### PR TITLE
esp: Add udp log endpoint

### PR DESCRIPTION
**Pull request by jhonnyam**
Implementation of a logging endpoint, using wifi transmission and udp to send log messages.

This PR depends on #42

### CODE REVIEW

**Comment by nopeslide** [comment]
would wait with the review until the #42 is merged, so we can rebase this PR

**Comment by ikstream** [comment]
Should we restart this @jhonnyam @nopeslide , or is this already included in a different PR?

**Comment by nopeslide** [comment]
@ikstream
I think this will be completely renewed, would close this if @jhonnyam does not protest

**Comment by jhonnyam** [comment]
> @ikstream
> I think this will be completely renewed, would close this if @jhonnyam does not protest

Yes, please close it.

**Pull request closed without merging**
