### PR TITLE
New repo structure

### PR DESCRIPTION
**Pull request by nopeslide**
## Related Issues & PRs

none

## Description

- restructured the whole repository
- this repository is no pure code repository anymore

## Context

Restructured this repo, so we are able to accommodate other contributions than esp32 code.
This is the first step towards moving the repo to cadus.

## Testing

- [x] tested all targets

## Documentation

---
---
# Repository structure overview

The [*LifeSensor*](https://lifesensor.org) project is an open-source, modular, low-cost bio sensing platform.

- This project is a collection of [*parts*](./parts/) and [*products*](./products/).
- [*Parts*](./parts/) are components that provide a set of features.
- [*Products*](./products/) are [*LifeSensor*](https://lifesensor.org) devices consisting of [*parts*](./parts/).
- [*Parts*](./parts/) are subjects to requirements and constraints imposed by [*products*](./products/) and other [*parts*](./parts/).

---
## Directories

See [Structure.md](./Structure.md) for an overview on how this repository is organized.

### [docker/](./docker/)
- Docker images used by this project
- Every used toolchain exists as docker image

### [docs/](./docs/)
- Documents regarding the whole project

### [parts/](./parts/)
- [*LifeSensor*](https://lifesensor.org) components used to build [*products*](./products/)

### [products/](./products/)
- [*LifeSensor*](https://lifesensor.org) devices consisting of [*parts*](./parts/)

# New Project structure overview & rules
---
## General project structure
- The project consists of *components*
- *Components* reside inside the root of the repository
- All *component* directories should feature a README.md
- All *component* directories should feature a Makefile

```
lifesensor
│
├── README.md                 : main README.md of the project
├── Makefile                  : Makefile executing targets in all components
│
├── CONTRIBUTING.md           : information on how to contribute
├── LICENSE.md                : license information
│
├── docs
│   ├── README.md             : list & description of project documents
│   ├── Makefile              : Makefile building/generating documents
│   └── ...  
│
├── <component name>          : component name
│   ├── README.md             : general description of the component,
│   │                           its structure and a list of all subcomponents
│   ├── Makefile              : Makefile executing targets in all subcomponents
│   │
│   ├── <subcomponent name>   : subcomponent name
│   │   ├── README.md         : general description of the subcomponent
│   │   │                       and list of all subcomponent variants
│   │   ├── Makefile          : Makefile bundeling all variants
│   │   │
│   │   ├── docs
│   │   │   ├── README.md     : list & description of subcomponent documents
│   │   │   ├── Makefile      : Makefile building/generating documents
│   │   │   └── ...  
│   │   │
│   │   ├── <variant>         : a variant is a non-exchangeable component
│   │   │   ├── README.md     : general description of the variant
│   │   │   ├── Makefile      : Makefile integrating component toolchain
│   │   │   │
│   │   │   ├── docs
│   │   │   │   ├── README.md : list & description of variant documents
│   │   │   │   ├── Makefile  : Makefile building/generating documents
│   │   │   │   └── ...  
│   │   │   └── ...
│   │   │
│   │   ├── <variant>
│   │   │   └── ...
│   │   └── ...  
│   │
│   ├── <subcomponent name>
│   └── ...  
│
├── <component name>
│   └── ...  
└── ...  
```

---
## README.md
- A README.md should link to all subdirectories that contain a README.md
- Links to directories should always end with a slash (`/`)
  - I.e `[dir/](./dir/)`
- Links should always have a relative prefix (`./`,`../`, ... )
  - I.e `[file.txt](./file.txt)`
- All README.md's should describe important Makefile targets
- All README.md's should describe the structure of subdirectories

---
## Makefiles
- All Makefiles should support the common targets.
  - `help`
    - show information about targets and variables
  - `all`
    - run common jobs (like `build` & `test`)
  - `check`
    - run all check jobs
    - *check* jobs are environment validations
    - I.e. check if toolchain is installed
  - `setup`
    - run all setup jobs
    - *setup* jobs are environment configurations
    - I.e. define devices to flash
  - `build`
    - run all build jobs
    - should not be dependent on any `setup` target
  - `test`
    - run all test jobs
    - should not be dependent on any `setup` target
  - `clean`
    - delete everything build
  - `distclean`
    - delete everything generated
    - should reset the state prior execution of any target
- All Makefiles should integrate Makefiles in subdirectories.
- Targets that fall in one of these target categories should be named
`<category>-<target>`.
  - I.e. `build-library`, `clean-library`, `test-library`, ...
- A Makefile should include the [.common.mk](./.make/common.mk) Makefile
to define these common targets.
  - simply add `include $(shell git rev-parse --show-toplevel)/.make/common.mk`
as last statement in the Makefile.

# Component docker

This directory contains Dockerfiles for the containers used in this project.

---
## List of images
- [base](./base/)
  - base image for all other images
- [idf](./idf/)
  - idf framework for the esp32 firmware
- [qemu](./qemu/)
  - qemu for architecture simulation

---
## Makefile

- `make help`
  - show Makefile options
- `make build`
  - build all versions of all images
- `make clean`
  - delete all volumes of all versions of all images
- `make distclean`
  - delete all all versions of all images

---
## Run a container
1. change into the version directory of the image
2. run `make run`
   - you may specify additional options, see `make help` for more information
   - you may specify `EXEC` to run a single command
     - i.e. `make run EXEC='echo hello world'`

---
## Adding new images
- If you want to add a new image,
please copy and modify the [Template](./.template/)

---
## Structure
```
.
├── README.md              : mandatory README.md you are currently reading
├── Makefile               : mandatory Makefile executing targets in all subdirs
│
├── <image name>           : mandatory unique name of the image
│   ├── README.md          : mandatory general description of the image
│   │                        and elaboration of differences between version
│   ├── Makefile           : mandatory Makefile executing targets in all subdirs
│   │
│   ├── <image version>    : mandatory unique image version
│   │   ├── README.md      : mandatory version specific description of the image,
│   │   │                    should list all features
│   │   ├── Makefile       : mandatory Makefile for integration of the image
│   │   ├── Dockerfile     : mandatory Dockerfile to build image
│   │   └── ...
│   │
│   ├── <image version>
│   │   └── ...
│   └── ...
│
├── <image name>
│   └── ...
└── ...
```

---
## Rules
- *Docker images* of the LifeSensor project should have a dedicated directory here.
- *Docker images* can be based on each other (see [base](./base/) image).
- *Docker images* may compete for the same functionality.
  - Different [*parts*](../parts/) may use different *docker images*
- *Docker images* should follow the directory scheme defined by the [*template image*](./.template/)
  - *Docker images* may contain any additional files & directories

# Component parts
*Parts* are components which are used as building blocks of [*products*](../products/).

---
## List of parts
- [interconnect](./interconnect/)
  - interconnect between pcbs
- [esp32-firmware](./esp32-firmware/)
  - firmware for the Esp32
- [esp32-components](./esp32-components/)
  - components of the esp32 firmware

---
## Makefile

- `make help`
  - show Makefile options
- `make all`
  - build all versions of all parts
- `make build`
  - build all versions of all parts
- `make test`
  - test all versions of all parts
- `make clean`
  - clean all versions of all parts
- `make distclean`
  - distclean all versions of all parts

---
## Adding new parts
- If you want to add a new part,
please copy the [*template part*](./.template/) and modify your copy.

---
## Structure

```
.
├── README.md              : mandatory README.md you are currently reading
├── Makefile               : mandatory Makefile executing targets in all subdirs
│
├── <part name>            : mandatory unique name of the part
│   ├── README.md          : mandatory general description of the part
│   │                        and elaboration of differences between version
│   │
│   ├── <part version>     : mandatory unique part version
│   │   ├── README.md      : mandatory version specific description of the part,
│   │   │                    should list all features
│   │   │
│   │   ├── Makefile       : mandatory Makefile for integration of the part
│   │   │
│   │   ├── code           : optional parent directory of any source code and build system files
│   │   │   │                i.e. firmware
│   │   │   ├── README.md  : description of the source code
│   │   │   └── ...
│   │   │
│   │   ├── docs           : optional parent directory for documents
│   │   │   │                i.e. documentation, datasheets
│   │   │   ├── README.md  : description of documents
│   │   │   └── ...
│   │   │
│   │   ├── kicad          : optional parent directory for kicad files
│   │   │   │                i.e. project files, schematics
│   │   │   ├── README.md  : description of the kicad files
│   │   │   └── ...
│   │   │
│   │   ├── mechanics      : optional parent directory for mechanic files
│   │   │   │                i.e. 3D-printer models
│   │   │   ├── README.md  : description of the mechanics files
│   │   │   └── ...
│   │   │
│   │   ├── requirements   : mandatory parent directory for requirements
│   │   │   │                used by requirement management tools
│   │   │   ├── README.md  : description of requirements
│   │   │   └── ...
│   │   │
│   │   └── scripts        : optional parent directory of part specific helper scripts
│   │       │                i.e. documentation generation, calculators
│   │       ├── README.md  : description of scripts
│   │       └── ...
│   │
│   ├── <part version>
│   │   └── ...
│   └── ...
│
├── <part name>
│   └── ...
└── ...
```

---
## Rules
- *Parts* of the LifeSensor project should have a dedicated directory here.
- *Parts* should not include other *parts*, instead they should refer to other *parts*.
- *Parts* may compete for the same functionality.
  - Different [*products*](../products/) may choose different *parts*
- *Parts* should follow the directory scheme defined by the [*template part*](./.template/)
  - *Parent directories* may contain any structure
  - Optional *parent directories* can be removed
- Only non-breaking changes may be introduced as patch for a *part*
- *Part versions* denote non-backwards-compatible variants of the same *part*
  - If major implementations change, consider creating a new *part* or *part version*
- *Part versions* should never denote the state of the *part*
  - All *part versions* should provide their intended functionality

---
## F.a.q
- Why no hierarchical structure?
  - *Parts* may implement multiple features therefore can't be sorted by distinct features
  - *Parts* may consist of file from multiple categories (*code*, *mechanics*, ...) breaking these up makes things complicated
  - *Parts* may be outsourced in the future and reintegrated vai git submodules
- Why version directories inside git?
  - Git can deduplicate files therefore the internal structure isn't bloated
  - *Part versions* are not necessarily incremental changes
  - This repo aims to support multiple [*products*](../products/) at once which may require different versions of *parts*

# Component products
*Products* are supported [*LifeSensor*](https://lifesensor.org) devices consisting of [*parts*](../parts/).

---
## Products
- [prototype/](./prototype/)
  - prototype & testing ground of various parts

---
## Products structure

```
lifesensor/products
│
├── README.md              : mandatory README.md you are currently reading
├── Makefile               : mandatory Makefile executing targets in all subdirs
│
├── <product name>         : mandatory unique name of the product
│   ├── README.md          : mandatory general description of the product
│   │                        and elaboration of differences between version
│   │
│   ├── <product version>  : mandatory unique product version
│   │   ├── README.md      : mandatory version specific description of the product,
│   │   │                    should list all features
│   │   │
│   │   ├── Makefile       : mandatory Makefile for integration of the product
│   │   │
│   │   ├── docs           : optional parent directory for documents
│   │   │   │                i.e. documentation, datasheets
│   │   │   ├── README.md  : description of documents
│   │   │   └── ...
│   │   │
│   │   └── requirements   : mandatory parent directory for requirements
│   │       │                used by requirement management tools
│   │       ├── README.md  : description of requirements
│   │       └── ...
│   │
│   ├── <product version>
│   │   └── ...
│   └── ...
│
├── <product name>
│   └── ...
└── ...
```

---
## Makefile

- `make help`
  - show Makefile options
- `make all`
  - build & test all products
- `make build`
  - build all products
- `make test`
  - test all products
- `make clean`
  - clean all products
- `make distclean`
  - distclean all products

---
## Adding new products
- If you want to add a new product,
please copy the [*template product*](./.template/) and modify your copy.

---
## Rules
- *Products* of the [*LifeSensor*](https://lifesensor.org) project should have a dedicated directory here.
- *Products* should not include [*parts*](../parts/) or other *products*
- *Products* may compete for the same functionality.
  - Different *products* may choose different [*parts*](../parts/) to achieve the same
- *Products* should follow the directory scheme defined by the [*template product*](./.template/)
  - *Parent directories* may contain any structure
  - Optional *parent directories* can be removed
- Only non-breaking changes may be introduced as patch for a *product*
- *Products versions* denote non-backwards-compatible variants of the same *product*
  - If major implementations change, consider creating a new *product* or *product version*
- *Products versions* should never denote the state of the *product*
  - All *product versions* should provide their intended functionality

### CODE REVIEW

**Comment by ikstream** [comment]
Should we merge the existing PRs, before we start the restructuring?

**Comment by nopeslide** [comment]
> Should we merge the existing PRs, before we start the restructuring?

I just moved the src files around, all PRs should be rebasable.
Would merge this first and then rebase all open PRs

**Review by ikstream — DISMISSED** [review]
lgtm 

If no one wants changes, I am going to merge this.

Fine with you @jhonnyam @reporiot

**Review by ikstream — DISMISSED** [review]

**Comment by nopeslide** [comment]
@ikstream are you ok with the commit msg?

**Review by ikstream — APPROVED** [review]
lgtm

**Pull request merged**
