### PR TITLE
added simulation of firmware via qemu

### PR DESCRIPTION
**Pull request by nopeslide**
## Related Issues & PRs

- none

## Description

- [x] qemu makefile target
- [x] gdb makefile target (connects to qemu)
- [x] qemu image generation
- [x] CI flavor of project for github actions

## Context

Testing is now possible without actual hardware via simulation.

## Testing

- [x] make qemu
- [x] make build
- [x] make qemu-image
- [x] make qemu-gdb
- [x] make gdb-qemu

## Documentation

- [x] documentation in /README.md
- [x] documentation in /lifesensor_ci/README.md

### CODE REVIEW

**Review by ikstream — CHANGES_REQUESTED** [review]
So far it looks good to me, but as this is a pretty big change, this would need extensive testing.
@pascalharp @jhonnyam  @reporiot could you please test as well and report if everything is working as expected?

**Comment by nopeslide** [comment]
cleaned up PR and squashed base PR for readability

**Comment by nopeslide** [comment]
rebased on current master, needs to be retested

**Comment by ikstream** [comment]
@jhonnyam @reporiot @pascalharp please test and report as well

**Comment by nopeslide** [comment]
rebased on master

**Review by ikstream — APPROVED** [review]

**Pull request merged**
